version: '3.8'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysql
    stop_grace_period: 3s
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}